### ISSUE TITLE
Results returned in alphabetical order, not in query order

### ISSUE THREAD

**Issue by randyzwitch** [Quansight/jupyterlab-mapd#22]
Feels like the columns should be returned in the order they are written in the query

<img width="690" alt="screen shot 2018-08-24 at 12 23 24 pm" src="https://user-images.githubusercontent.com/2762787/44595937-94e98680-a798-11e8-9c05-da8cf4d875f7.png">

**Comment by ian-r-rose** [comment]
Yep, agreed! I'll look into fixing that.
